### ISSUE TITLE
Permission issue with mounted volume for /data and /datalog

### ISSUE THREAD

**Issue by AlbinOS** [31z4/zookeeper-docker#1]
I'm trying to use filesystem persistency in Docker using the mounting option when running the zookeeper image :

`sudo docker run --name zookeeper --restart always -d -v /data/castle/zookeeper/data:/data -v /data/castle/zookeeper/datalog:/datalog zookeeper`

Here is the error raised by the container : 

```
/docker-entrypoint.sh: line 29: /data/myid: Permission denied
/docker-entrypoint.sh: line 29: /data/myid: Permission denied
/docker-entrypoint.sh: line 29: /data/myid: Permission denied
/docker-entrypoint.sh: line 29: /data/myid: Permission denied
/docker-entrypoint.sh: line 29: /data/myid: Permission denied
/docker-entrypoint.sh: line 29: /data/myid: Permission denied
/docker-entrypoint.sh: line 29: /data/myid: Permission denied
```

As everything is ran by Docker, I configured everything to be owned by root and only read/write by root :

```
/data/castle/zookeeper# ls -l
drwx--x--x 2 root root 4096 Sep 30 17:06 data
drwx--x--x 2 root root 4096 Sep 30 17:07 datalog
```

For example, it works very well with the official Redis image. The Redis folder : 

`drwx--x--x 2 systemd-timesync root 4096 Sep 30 16:55 redis/`

Do you have any idea how to get that running without compromising security of the data folder ?

**Comment by 31z4** [comment]
@AlbinOS thanks for your report!

**Comment by AlbinOS** [comment]
Just tested it, it works perfectly now. Thanks a lot @31z4 for the good work !
