### ISSUE TITLE
add admin.serverPort option for host network mode

### ISSUE THREAD

**Issue by hozumi** [31z4/zookeeper-docker#108]
### Expected behavior

When running docker image as `--net=host` , it is helpful if the docker image has a way to specify `admin.serverPort` ,which is 8080 by default, by passing value via environment variable in order to avoid port collision.

### Actual behavior

Currently there is no option to specify `admin.serverPort` parameter.
So if 8080 port is used by another program, users must set false to `admin.enableServer` in case of `--net=host` mode.

**Comment by 31z4** [comment]
I believe you can you `ZOO_CFG_EXTRA ` for that. See 
https://hub.docker.com/_/zookeeper/

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/3657959/88552324-66881c00-d03d-11ea-8138-87f1012e8f12.png">

So it would be `docker run -e ZOO_CFG_EXTRA="admin.serverPort=1234" zookeeper`.

**Comment by hozumit** [comment]
@31z4 I missed that parameter. Thank you for your answer! Please close this issue.

**Comment by hozumi** [comment]
@31z4 I missed that parameter. Thank you for your answer!
