### ISSUE TITLE
Making Zookeeper ISTIO friendly

### ISSUE THREAD

**Issue by shikanon** [31z4/zookeeper-docker#117]
Unable to make zookeeper running within an ISTIO Service mesh due to the the restriction of `quorumListenOnAllIPs` parameter in zookeeper config to be false by default without an ability to set it on to true through an environment variable.
can look this page: https://istio.io/latest/faq/applications/

### Expected behavior

Making the docker image istio friendly by allowing zookeeper configuration `quorumListenOnAllIPs` as an environment variable.
set quorumListenOnAllIPs=true to make istio friendly like this 

https://github.com/shikanon/zookeeper-docker/commit/82960df87f882242f7c6eea7e60a7245325630fa

**Comment by 31z4** [comment]
If you want to set some additional configuration parameters that are not covered by the image environment variables you can use `ZOO_CFG_EXTRA` environment variable for that. See https://hub.docker.com/_/zookeeper/

![](https://user-images.githubusercontent.com/3657959/93694702-6cbfe380-fb28-11ea-8016-3813b2e29493.png)

So, in your case it would be

```console
$ docker run --name some-zookeeper --restart always -e ZOO_CFG_EXTRA="quorumListenOnAllIPs=true" zookeeper
```
