### ISSUE TITLE
zookeeper 3.7.0

### ISSUE THREAD

**Issue by qeepcologne** [31z4/zookeeper-docker#119]
i tried to update to 3.7 via modifying DISTRO_NAME and SHORT_DISTRO_NAME, but then gpg check fails.

**Comment by qeepcologne** [comment]
gpg server is just slow/down

**Comment by 31z4** [comment]
I've added `3.7`. I'll be available in Docker Hub once https://github.com/docker-library/official-images/pull/9922 is merged.
