### ISSUE TITLE
Upgrade to 3.6.3

### ISSUE THREAD

**Issue by bianjp** [31z4/zookeeper-docker#121]
3.6.3 is released on 13 April, 2021 including multiple CVE fixes: https://zookeeper.apache.org/doc/r3.6.3/releasenotes.html

**Comment by rjduffner** [comment]
@31z4 any issues with this issue or associated pr?

Thank you!

**Comment by 31z4** [comment]
Hi @bianjp thanks for you contribution. And sorry guys for the delayed response. The image will be updated once https://github.com/docker-library/official-images/pull/10266 is merged.
