### ISSUE TITLE
override JDK on zookeeper 3.4.9

### ISSUE THREAD

**Issue by fazaza** [31z4/zookeeper-docker#123]
Hi,

We have custom zookeeper docker image based on 3.4.9 ( openjdk:8 ), deployed on customer since years
```

FROM zookeeper:3.4.9

COPY zkGenConfFileAndStart.sh zkStartServer.sh /
RUN chmod +x /*.sh
...
...

CMD ["/zkStartServer.sh"]
```

now we want to override the JDK version and move to openjdk-15.0.1

if there is a simple way to override the jdk version for zookeeper 3.4.9

**Comment by 31z4** [comment]
Hi @fazaza and sorry for the delayed response. I don't think there's a simple way to override the JDK version aside from forking this repo and building a custom image.

**Comment by azazadev** [comment]
Thanks @31z4 for your answer, How I can fork the 3.4.9 repo ? it's removed from this git
