### ISSUE TITLE
how to config other parameters

### ISSUE THREAD

**Issue by zziawan** [31z4/zookeeper-docker#124]
how to config zookeeper other parameter, for example "preAllocSize", it does not found in env .  And when i chanaged the "autopurge.purgeInterval" by env paramters ,it does not change in zoo.cfg.  The change can work? thanks!

**Comment by wh12** [comment]
hi,  I think you can configure it via ZOO_CFG_EXTRA

**Comment by zziawan** [comment]
> hi, I think you can configure it via ZOO_CFG_EXTRA

found it ,thanks!

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.
