### ISSUE TITLE
Zookeeper 3.8.0 not available

### ISSUE THREAD

**Issue by der-eismann** [31z4/zookeeper-docker#130]
### Expected behavior

An image with zookeeper 3.8.0 should be available. It was [released on 25.02.](https://archive.apache.org/dist/zookeeper/zookeeper-3.8.0/), it's about time for an image :slightly_smiling_face: 

### Actual behavior

There is none

**Comment by Slach** [comment]
@31z4 could you look this issue?

**Comment by Slach** [comment]
@31z4 thanks a lot for your efforst
when expect update of https://github.com/docker-library/official-images/blob/master/library/zookeeper?

**Comment by 31z4** [comment]
You're welcome 😊 New tag will be available once https://github.com/docker-library/official-images/pull/12091 is merged.
