### ISSUE TITLE
container start failed: /docker-entrypoint.sh: permission denied:unknown

### ISSUE THREAD

**Issue by yuezhongtao** [31z4/zookeeper-docker#133]
***Before you file an issue here, please keep in mind that your issue may be not related to the image itself. Please make sure that it is, otherwise report the issue [upstream](https://issues.apache.org/jira/projects/ZOOKEEPER/issues).***

### Expected behavior
container start success.
Tell us what should happen.

### Actual behavior

Tell us what happens instead.
<img width="1265" alt="企业微信截图_02cf203c-87d9-400a-b214-331eee57d958" src="https://user-images.githubusercontent.com/18341274/164584747-c2930f3a-5d2c-4963-aed0-1e23d1bd7c07.png">

### Steps to reproduce the behavior
- build zookeeper 3.8.0 image on local machine
- start container instance with default config
- start failed

Tell us how to reproduce the issue.

### System configuration

Please include as much relevant information as possible.

**Comment by yuezhongtao** [comment]
I have figured out the cause of the problem, docker packaging will not change the permissions of the file. It is because my local newly created docker-entrypoint.sh does not have executable permission. i think dockerfile can be hardened.

**Comment by 31z4** [comment]
While it's possible to add `RUN chmod +x /docker-entrypoint.sh` into the `Dockerfile` I don't think it's worth an extra image layer. If you're building the image using a newly created `docker-entrypoint.sh` please make sure it's executable on the host.
