### ISSUE TITLE
Zookeeper 3.5.10 image

### ISSUE THREAD

**Issue by alexangas** [31z4/zookeeper-docker#141]
As it contains various CVE fixes, could we please have a [Zookeeper 3.5.10](https://zookeeper.apache.org/doc/r3.5.10/releasenotes.html) image put up on Docker Hub?

**Comment by 31z4** [comment]
Sure! It'll be available on Docker Hub once [this PR](https://github.com/docker-library/official-images/pull/13894) is merged.
