### ISSUE TITLE
Upgrade to JRE 17, pin Ubuntu release

### ISSUE THREAD

**Issue by janhoy** [31z4/zookeeper-docker#143]
JRE11 is end of life. Upgrade to 17 in the image.

In the Solr project we recently started pinning Linux/Ubuntu version of our images, since the `eclipse-temurin:jre-xx` base images gets auto updated on new ubuntu major releases. We chose to pin to Ubuntu "focal" release for max compatibility, see https://solr.apache.org/news#solr-docker-images-now-pin-the-linux-release and https://github.com/apache/solr-docker/pull/13

We should pin ubuntu release as "jammy", and do an active choice to bump it at a later time.

**Comment by ICHx** [comment]
Just came across the same issue.  On my env with Server Version: 18.09.3, JVM refuse to run when base image is ubuntu 22.04
