### ISSUE TITLE
Add ppc64le to docker official image

### ISSUE THREAD

**Issue by Balavva-Mirji** [31z4/zookeeper-docker#150]
Hi @31z4 , Could you please help in adding ppc64le in the docker official image for Zookeeper?
The latest base image `eclipse-temurin:11-jre` has [ppc64le support](https://hub.docker.com/layers/library/eclipse-temurin/11-jre/images/sha256-45d7751ee5c8e11319012f0581d920dfd09d3b912e85a5d57a47622c5f092c49?context=explore).
Please let me know if anything is needed from our side.
Thank you!

**Comment by 31z4** [comment]
Hi @Balavva-Mirji, `ppc64le` support will be added once https://github.com/docker-library/official-images/pull/14942 is merged.

**Comment by Balavva-Mirji** [comment]
@31z4 Thanks much!
