### ISSUE TITLE
zookeeper docker 3.9.0

### ISSUE THREAD

**Issue by wilsonswee** [31z4/zookeeper-docker#153]
Hello,

We found some docker OS level vulnerabilities in your latest release. Any chance there will be a Docker rebuild with the OS vulnerabilities fixes?

Regards,
Wilson

**Comment by 31z4** [comment]
Yup the rebuild should happen automatically when the base image updates. Although, it may take some time unless there's a critical security need. See more details here: https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.
