### ISSUE TITLE
Re-releasing Docker images with the same number causes issues

### ISSUE THREAD

**Issue by ateska** [31z4/zookeeper-docker#161]
The team here re-releases new images od Zookeeper Docker image under the same version.
It leads to unexpected re-installation of running Zookeeper server even if the specific version is pinned (ie in a `docker-compose.yaml`).
If this happens in the cluster, it can result in a catastrophic failure - and it is a hard thing to catch, b/c the new existing image can be released any time; even after the rollout is planned and tested.

**To Reproduce**
Do "docker compose up" when new already existing version of a Zookeeper docker image is released.

**Expected behavior**
The newly released version has a new version number.

**System configuration**
Normal docker or docker-compose environment.

**Additional context**
Zookeeper is typically a core of the cluster so that unexpected update during seemingly unrelated work be bad.

**Comment by 31z4** [comment]
All official Docker images gets automatically rebuilt if a base image changes. It's done mostly to address security issues.

You can also pin image checksum to completely disable any updates. E.g., `zookeeper:3.9.1-jre-17@sha256:df778d0ffaca958ae85ed22cca19f5afb73609d241aa8e717ece2a778bb2645e`.

**Comment by ateska** [comment]
Oh, ok.
Thank you.
