### ISSUE TITLE
i use command "docker run -d zookeeper" but got an error : standard_init_linux.go:187: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by wind634** [31z4/zookeeper-docker#19]

**Comment by wind634** [comment]
a few days ago is ok, but now i use the office zookeeper image get the error

**Comment by wind634** [comment]
i try again. use " docker run --name some-zookeeper --restart always -d 31z4/zookeeper  " is ok but use "docker run --name some-zookeeper --restart always -d zookeeper  " is not ok

**Comment by 31z4** [comment]
@wind634 are you sure you're running on x86_64? This is the only platform supported by the image.

**Comment by 31z4** [comment]
Closing this because there is not enough information.
