### ISSUE TITLE
ppc64le dockerhub images

### ISSUE THREAD

**Issue by vaibhavsood** [31z4/zookeeper-docker#20]
Hi, I'm looking to enable docker containers for packages like zookeeper for multiple architectures on dockerhub, starting off with a focus on ppc64le. Wanted to check on the work that will be involved to do that

I have locally been able to successfully test ppc64le changes to the dockerfiles in this repo - changes for enabling additional arch would be minimum, however the base image might be a problem as mentioned in issue #7 but that can eventually be resolved

However I want to understand if this community is open to supporting ppc64le images officially. The official images have this method for enabling multi-arch : https://github.com/docker-library/official-images#multiple-architectures, as mentioned there they recommend having a single dockerfile with swithches for arch-specific changes.

The steps would involve getting the single dockerfile here to include ppc64le and then subsequently raising a PR under docker-library/official-images (would mostly need changes to the metadata file https://github.com/docker-library/official-images/blob/master/library/zookeeper)

I'm willing to work on these steps, want to know if community is okay with it or any other thoughts

Thanks!

**Comment by 31z4** [comment]
Hey @vaibhavsood adding multi-arch support would be much appreciated!

Any reason of duplicating the original issue #7? I'd love to continue work there and close this as a duplicate if you're okay with this.

I didn't get this "single dockerfile" thing. Could you please explain what exactly should be changed?

**Comment by vaibhavsood** [comment]
Hi @31z4 , thanks for the response! I have updated issue #7 accordingly, closing this. 

The single dockerfile is a requirement for multi-arch by docker official (as described here: https://github.com/docker-library/official-images#multiple-architectures, basically all arch-specific code to be in a single Dockerfile instead of separate Dockerfile's for each arch)
