### ISSUE TITLE
su instead of su-exec

### ISSUE THREAD

**Issue by 1605200517** [31z4/zookeeper-docker#29]
su-exec is a third-party Alpine package i.e. not a part of GNU neither Apache project:
https://github.com/ncopa/su-exec

Therefore, I thought maybe it can work just with su as well

https://github.com/bigdata-central/zookeeper-docker/blob/ubuntu/3.4.10/docker-entrypoint.sh 

(thanks to DevOps SE https://devops.stackexchange.com/questions/2526/interference-of-docker-cmd-with-su-works-with-su-exec-but-not-with-su)

**Comment by 31z4** [comment]
The main motivation for not using `su` is that it spawns a child process
```console
$ docker run -it --rm zookeeper su -c 'ps aux'
PID   USER     TIME   COMMAND
    1 root       0:00 ash -c ps aux
    8 root       0:00 ps aux
```
while `su-exec` does not
```console
$ docker run -it --rm zookeeper su-exec root ps aux
PID   USER     TIME   COMMAND
    1 root       0:00 ps aux
```
And as it's said in https://github.com/tianon/gosu and https://github.com/ncopa/su-exec this might introduce some TTY and signal-forwarding issues.
