### ISSUE TITLE
zookeeper log directory incorrectly specified 

### ISSUE THREAD

**Issue by Jesse-Cameron** [31z4/zookeeper-docker#33]
Hello,

Noticed a minor issue when using this docker container. The environment variable for the log directory is incorrect. It's set as `ZOO_DATA_LOG_DIR` where it should instead be `ZOO_LOG_DIR` as per [here](https://github.com/apache/zookeeper/blob/ec20c5434cc8a334b3fd25e27d26dccf4793c8f3/bin/zkEnv.sh#L70).

If this isn't set correctly, you have issues with the reading logs!

**Comment by Jesse-Cameron** [comment]
I've added a quick PR and tested on my machine. 
Can confirm that it worked for all three supported versions.

Let me know what you think! 🔥

**Comment by 31z4** [comment]
Hey @Jesse-Cameron! Sorry for the delay and thanks for reporting this!
`ZOO_DATA_LOG_DIR ` is meant for the transaction log, not the regular service logs. It's used to pass the value to the `docker-entrypoint.sh` and write it to the config file [here](https://github.com/31z4/zookeeper-docker/blob/master/3.4.11/docker-entrypoint.sh#L17).

By default all Zookeeper logs go to the standard output in this image, so you should not bother about reading the logs from `$ZOOKEEPER_PREFIX/logs`. But if you really want to you may want to check this [PR](https://github.com/31z4/zookeeper-docker/pull/24) which wasn't finished by the author.

But again, when running in Docker it's common practice to redirect all logs to the standard output and then gather/aggregate those logs with special drivers and tools.

**Comment by Jesse-Cameron** [comment]
Hi Elisey,

Thanks for getting back to me. Great to hear your thoughts on the repo. I totally agree that for the most part that docker containers should redirect all logs to stdout. Makes things much easier downstream. I also didn't realised that `ZOO_DATA_LOG_DIR` was a transactional dir. Good to know. 

However, in my experience with zk, not having `ZOO_LOG_DIR` gives rise to another issue. That, for whatever reason, it needs to be configured in order to write the `data/zookeeper.pid` file. If you ever want to issue graceful shutdowns (via `zkServer.sh stop`) this file is required.

I understand that this is your repo and it's up to you, but I would like to suggest is that:
1. Both `ZOO_DATA_LOG_DIR` and `ZOO_LOG_DIR` are set. Potentially renamed to avoid confusion.
2. The logs in `ZOO_LOG_DIR` be piped through to stdout via `tail -f` or some other utility.

Looking forward to hearing your thoughts,
Jesse

**Comment by 31z4** [comment]
Jesse,

> However, in my experience with zk, not having ZOO_LOG_DIR gives rise to another issue. That, for whatever reason, it needs to be configured in order to write the data/zookeeper.pid file. If you ever want to issue graceful shutdowns (via zkServer.sh stop) this file is required.

I'm not sure I understand how `ZOO_LOG_DIR ` could affect `zookeeper.pid`. The default location of this file is [`$ZOO_DATADIR/zookeeper_server.pid`](https://github.com/apache/zookeeper/blob/fb7ddacfc42acb01275ca8d69ae219d6413832b4/bin/zkServer.sh#L136). Moreover, since we start Zookeeper in foreground, this file is not needed. And when you stop the container `SIGTERM` is sent to the process, which is exactly what `zkServer.sh stop` does. So stoppping the container equals gracefull shutdown.

> Both ZOO_DATA_LOG_DIR and ZOO_LOG_DIR are set. Potentially renamed to avoid confusion.

As I mentioned earlier you could take a look at [this PR](https://github.com/31z4/zookeeper-docker/pull/24) and try to resurect it.

> The logs in ZOO_LOG_DIR be piped through to stdout via tail -f or some other utility.

This looks like a bit of a hack. I think a proper way of doing this would be via [log4j](https://github.com/apache/zookeeper/blob/master/conf/log4j.properties).

**Comment by hlwanghl** [comment]
@Jesse-Cameron `ZOO_LOG_DIR` was introduced recently, and you can take a look here:
https://github.com/31z4/zookeeper-docker#how-to-configure-logging

**Comment by Jesse-Cameron** [comment]
@hlwanghl Thanks for the update! Excited to try this out! 👍
