### ISSUE TITLE
Add tag 3.4.12

### ISSUE THREAD

**Issue by dsw9742** [31z4/zookeeper-docker#36]
New stable release is out, and it contains a lot of fixes (including [regressions introduced in 3.4.11](https://issues.apache.org/jira/browse/ZOOKEEPER-2960)).
http://zookeeper.apache.org/doc/r3.4.12/releasenotes.html
Let me know if I can help.

**Comment by dsw9742** [comment]
Thank you for adding the new the new tag. Question for you: its very possible I misunderstand the relationship between this repository and Docker Hub, but should there be a 3.4.12 image available at  [official Zookeeper](https://hub.docker.com/_/zookeeper/) if there is a 3.4.12 tag here?

**Comment by 31z4** [comment]
Hey @dsw9742  Sorry for confusion here. The image makes it to the Docker Hub once the corresponding https://github.com/docker-library/official-images PR (https://github.com/docker-library/official-images/pull/4351) is merged. It's been merged just recently.
