### ISSUE TITLE
Trying to install offline

### ISSUE THREAD

**Issue by AAAarrrgggg** [31z4/zookeeper-docker#44]
Hi team. I'm kinda new to Docker and I'm trying to set up a zookeeper cluster on an offline environment. 

My problem is that I can't pull via docker, so I downloaded the zookeeper-3.4.12.tar.gz directly from the repository. 

And when I try to load the image, as I did for the UCP module, onto my docker I get this json error :
 docker load < /root/zookeeper-3.4.12.tar.gz
open /var/lib/docker/tmp/docker-import-242583754/zookeeper-3.4.12/json: no such file or directory

I'm guessing I'm doing something wrong because in your docker file there as wget for an asc file aswell. ( at the minimum, this, is wrong ) 

Is it possible to get a little bit of guidance ? 

Regards,
Newt

**Comment by 31z4** [comment]
One possible solution would be pulling the image on a machine that is connected to the internet and saving this image.

    docker pull zookeeper
    docker save --output image.tar zookeeper

You can then move the archive to your offline environment and load it.

    docker load --input image.tar

**Comment by 31z4** [comment]
Please refer to the Docker documentation for more information. Closing the issue as unrelated to the image.
