### ISSUE TITLE
Key not found in store.

### ISSUE THREAD

**Issue by Maybrittnelson** [31z4/zookeeper-docker#51]
### Expected behavior
zookeeper can run
### Actual behavior
zookeeper can't run
### Steps to reproduce the behavior
$ docker run --name myZookeeper --restart always -d 31z4/zookeeper
86ce613f9a90a3334a01875b4e57e724ac30d23f26277c3982d9034e8e1f0943
docker: Error response from daemon: failed to update store for object type *libnetwork.endpointCnt: Key not found in store.
### System configuration
centos7
docker Version:      17.03.1-ce 
zookeeper:latest

**Comment by 31z4** [comment]
The error doesn't seem related to the image. Please check you environment or report the issue to Docker.
