### ISSUE TITLE
gpg: keyserver receive failed

### ISSUE THREAD

**Issue by KarthikeyanODL** [31z4/zookeeper-docker#52]
### Expected behavior
 Docker Build Success.
 Should get the GPG key from  Key Server 

### Actual behavior
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-key C61B346552DC5E0CB53AA84F59147497767E7473
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: No keyserver available
+ gpg --keyserver pgp.mit.edu --recv-keys C61B346552DC5E0CB53AA84F59147497767E7473
gpg: keyserver receive failed: No keyserver available
+ gpg --keyserver keyserver.pgp.com --recv-keys C61B346552DC5E0CB53AA84F59147497767E7473
gpg: keyserver receive failed: No keyserver available

### Steps to reproduce the behavior

Clone the [Zookeeper](https://github.com/31z4/zookeeper-docker.git)
(master branch)
cd 3.4.13 
docker build -t zk .

### System configuration
"Ubuntu"
VERSION="18.04.1 LTS 
Please include as much relevant information as possible.

I want to build zookeeper official Docker image. 
I am facing error in GPG Key receiving . I checked in the key-server, C61B346552DC5E0CB53AA84F59147497767E7473 is not available.
I am not behind any proxy. 
Should I change GPG KEY in my Dockerfile ?
![err](https://user-images.githubusercontent.com/30072921/53611437-ed02b900-3c11-11e9-9c67-0014c87b1e1e.PNG)

Can anyone help ?

**Comment by 31z4** [comment]
Might be a temporary network issue. Sometimes it happens to the keyservers, that's why there are three of them.

It builds fine on my machine now. So closing this as it doesn't seem related to the image itself.
