### ISSUE TITLE
Dockerfile modification

### ISSUE THREAD

**Issue by alexsplashex** [31z4/zookeeper-docker#53]
Hi there.
Need to add this line before ENTRYPOINT section when building in docker-compose:

```RUN chmod +x /docker-entrypoint.sh && chown $ZOO_USER /docker-entrypoint.sh```

Without this got an error
```
Recreating zookeeper ... error

ERROR: for zookeeper  Cannot start service zookeeper: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied": unknown

ERROR: for zookeeper  Cannot start service zookeeper: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by 31z4** [comment]
Please follow the [issue template](https://github.com/31z4/zookeeper-docker/blob/master/.github/issue_template.md) or at least provide exact steps to reproduce the issue.

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.
