### ISSUE TITLE
dokcer run exec format error

### ISSUE THREAD

**Issue by qinxcb2015** [31z4/zookeeper-docker#54]
docker run --rm  \
 --name=zookser001 \
 --net=host \
 -e ZOO_USER=`whoami` \
 -e ZOO_MY_ID=1 \
 -e ZOO_DATA_DIR=/opt/zookeeper/data \
 -e ZOO_DATA_LOG_DIR=/opt/zookeeper/datalog \
 -e ZOO_LOG_DIR=/opt/zookeeper/logs \
 -e ZOO_SERVERS="server.1=zook001:2888:3888 server.2=zook002:2888:3888 server.3=zook003:2888:3888" \
   zook:3.5.4-beta

**Comment by qinxcb2015** [comment]
error info:

standard_init_linux.go:207: exec user process caused "exec format error"

**Comment by 31z4** [comment]
Closing this as not having enough information to reproduce the issue. Please follow https://github.com/31z4/zookeeper-docker/blob/master/.github/issue_template.md if you're still having troubles running the image.
