### ISSUE TITLE
Change in base image removed `nc` command commonly used in kubernetes liveness probes

### ISSUE THREAD

**Issue by dgrove-oss** [31z4/zookeeper-docker#66]
The change in base image from openjdk:8-jre-alpine to openjdk:8-jre-slim 4 days ago in 01d134a resulted in the `nc` command no longer being in the image.

This breaks a reasonable way to write liveness/readiness probes when this image is used to deploy zookeeper on Kubernetes that uses `nc` to send the `ruok` work to the zookeeper server.  For example `echo ruok | nc -w 1 localhost:2181 | grep imok` as a readiness probe.

Would you consider adding `nc` back into the image by adding it to the apt-get stanza in your Dockerfile?

**Comment by 31z4** [comment]
Hey @dgrove-oss, thanks for reporting this 👍 
I've added `netcat` to the image. Please wait util [this PR](https://github.com/docker-library/official-images/pull/6005) to the official images library is merged.
