### ISSUE TITLE
Not compatible with ppc64le Arch

### ISSUE THREAD

**Issue by harsha544** [31z4/zookeeper-docker#7]
Given that provided zookeeper docker image is built based on https://github.com/31z4/zookeeper-docker/blob/master/3.4.9/Dockerfile which relies on **openjdk:8-jre-alpine** and inturn is a x86_64 docker image, the "docker run -it zookeeper:3.49" fails with **exec format error** .

**Comment by 31z4** [comment]
Thank you for your report @harsha544! Unfortunately I don't have a machine to build, tests and maintain such images 😞  Feel free to contribute!

**Comment by 31z4** [comment]
This is definitely doable even on `x86` machine and [Building ARM containers on any x86 machine, even DockerHub](https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/) is a good strating point.

Pull requests are welcome!

**Comment by harsha544** [comment]
Thank you reopening the issue.

I have had success earlier in running on ppc64le container on x86_64 arch (and ofcourse other way around too), however I uncovered certain issues/limitations whilst installing a deb package and yet times bumped into issue whilst trying to run a service/daemon inside container.

I think it would be sane to get it working on ppc64le arch itself.

FWIW :- http://cloudgeekz.com/1352/powerpc-docker-images-on-intel.html

**Comment by vaibhavsood** [comment]
The zookeeper dockerfiles use openjdk:8-jre-alpine as the base image, however this is not multi-arch yet (as per this https://github.com/gliderlabs/docker-alpine/issues/304, similar problem with orientdb as per comment here: https://github.com/docker-library/official-images/pull/3480#issuecomment-331207438), would need to wait till the docker-alpine ticket is resolved

**Comment by vaibhavsood** [comment]
Hi, https://github.com/gliderlabs/docker-alpine/issues/304 has been resolved, ill work on the multi-arch changes

The first step would be to add to the dockerfiles here changes for other arch's, will raise a PR for this

**Comment by 31z4** [comment]
Progress has been made: https://github.com/docker-library/official-images/pull/3672

**Comment by vaibhavsood** [comment]
@31z4 Verified the new zookeeper container on ppc64le. 

https://github.com/docker-library/official-images/tree/master/test/tests/zookeeper-basics runs correctly on the ppc64le container, also did some basic validation manually

**Comment by 31z4** [comment]
That's great! Thanks a lot @vaibhavsood!

**Comment by harsha544** [comment]
@31z4 @vaibhavsood Thank you for your efforts. I am glad to see progress made in this direction, is my assumption correct that we have leveraged QEMU libraries and made this work ?

**Comment by 31z4** [comment]
@harsha544 I'm not sure. For additional details, please check https://github.com/gliderlabs/docker-alpine/issues/304
