### ISSUE TITLE
zkCleanup doesn't work due to bad permissions and environment variables not being available to the zookeeper user

### ISSUE THREAD

**Issue by KoenDG** [31z4/zookeeper-docker#73]
I recently had this conversation on the zookeeper mailing list:

https://mail-archives.apache.org/mod_mbox/zookeeper-user/201907.mbox/browser

Concerning the .log files not being cleaned up, despite setting purgeInterval.

From debugging this, I learned that the docker image does sets a bunch of environment variable which are not available to the zookeeper user. This can be tested by going into the container, switching users to the zookeeper user (`su - zookeeper`) and trying to echo those environment variables.

For instance, the zookeeper configuration dir is not set and this messes with zkEnv.sh. which tries to find it in /zookeeper-3.4.13/bin/../conf/

While actually, the docker image defines the file as being in /conf

The main issue though, is the cleanup of the log files plain not working. Even if you set the environment variables manually and execute the generated java command, the old logs are not cleaned up and nothing in terms of error is printed.

Looking for any kind of advice on this.

**Comment by 31z4** [comment]
Hi @KoenDG, thanks for reporting this!
Your conclusion regarding visibility of the environment variables to the zookeeper user doesn't seem correct. You used `su - zookeeper` which resets the environment by default.
```
$ docker run -it zookeeper:3.4 su -h
Usage: su [options] [LOGIN]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                make the shell a login shell
  -m, -p,
  --preserve-environment        do not reset environment variables, and
                                keep the same shell
  -s, --shell SHELL             use SHELL instead of the default in passwd
```
That's why you don't see the variables.

**Comment by KoenDG** [comment]
I have not yet. I'll try this later.

And thanks for pointing that out, I didn't know that about the usage of `su`.

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now. Feel free to re-open it if additional details are discovered.
