### ISSUE TITLE
Support enabling JMX port.

### ISSUE THREAD

**Issue by KoenDG** [31z4/zookeeper-docker#74]
In bin/zkServer.sh there is this bit of code:

```

if [ "x$JMXDISABLE" = "x" ] || [ "$JMXDISABLE" = 'false' ]
then
  echo "ZooKeeper JMX enabled by default" >&2
  if [ "x$JMXPORT" = "x" ]
  then
    # for some reason these two options are necessary on jdk6 on Ubuntu
    #   accord to the docs they are not necessary, but otw jconsole cannot
    #   do a local attach
    ZOOMAIN="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=$JMXLOCALONLY org.apache.zookeeper.server.quorum.QuorumPeerMain"
  else
    if [ "x$JMXAUTH" = "x" ]
    then
      JMXAUTH=false
    fi
    if [ "x$JMXSSL" = "x" ]
    then
      JMXSSL=false
    fi
    if [ "x$JMXLOG4J" = "x" ]
    then
      JMXLOG4J=true
    fi
    echo "ZooKeeper remote JMX Port set to $JMXPORT" >&2
    echo "ZooKeeper remote JMX authenticate set to $JMXAUTH" >&2
    echo "ZooKeeper remote JMX ssl set to $JMXSSL" >&2
    echo "ZooKeeper remote JMX log4j set to $JMXLOG4J" >&2
    ZOOMAIN="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=$JMXPORT -Dcom.sun.management.jmxremote.authenticate=$JMXAUTH -Dcom.sun.management.jmxremote.ssl=$JMXSSL -Dzookeeper.jmx.log4j.disable=$JMXLOG4J org.apache.zookeeper.server.quorum.QuorumPeerMain"
  fi
else
    echo "JMX disabled by user request" >&2
    ZOOMAIN="org.apache.zookeeper.server.quorum.QuorumPeerMain"
fi

```
And it will always end up in the first part with "# for some reason these two options are necessary on jdk6 on Ubuntu" in it.

With the default setup, this will never assign a port to JMX.

Which is related to this ticket: https://github.com/apache/zookeeper/pull/180

Where is it explained a snapshot can only be forced via JMX.

And then recently this discussion on the zookeeper mailing list: https://mail-archives.apache.org/mod_mbox/zookeeper-user/201907.mbox/%3CCAO05p7CHSbPxjRoPpQ1-E1eLVmS_6jpDRRRqWusJs1P%3DS4%2BUhA%40mail.gmail.com%3E

Resulting in this conclusion: https://mail-archives.apache.org/mod_mbox/zookeeper-user/201907.mbox/%3cC19A298D-A7A0-489E-B991-59314516D9C2@gmail.com%3e

Where it is explained you can't update from 3.4 to 3.5 without a snapshot. Which is why I need it.

So that's the nature of my problem and it seems I can only come here to get it fixed or explained.

EDIT: Link to mailing archive fixed.

**Comment by 31z4** [comment]
I'm not sure I understand what needs to be changed in the image to help resolve your issue.
If you need to set some environment variables then there's no need to make changes to the image. You just use `-e VAR=VALUE` flag of the `docker run` command.

**Comment by KoenDG** [comment]
Right, odd that that didn't occur to me. My bad.
