### ISSUE TITLE
clientPort  2181 can't telnet

### ISSUE THREAD

**Issue by ColaMachine** [31z4/zookeeper-docker#78]
***Before you file an issue here, please keep in mind that your issue may be not related to the image itself. Please make sure that it is, otherwise report the issue [upstream](https://issues.apache.org/jira/projects/ZOOKEEPER/issues).***

### Expected behavior

docker run --name my_zookeeper -d -p 2181:2181 -p 2888:2888 -p 3888:3888  --env ZOO_MY_ID=1 --env ZOO_SERVERS="server.1=0.0.0.0:2888:3888 server.2=192.168.154.33:5889:5890 server.3=192.168.213.91:2888:3888" zookeeper:latest

and the client port 2181 can't telnet 

### Actual behavior

i found the /conf/zoo.cfg does not  cotain client port item

### Steps to reproduce the behavior

Tell us how to reproduce the issue.

### System configuration

dataDir=/data
dataLogDir=/datalog
tickTime=2000
initLimit=5
syncLimit=2
autopurge.snapRetainCount=3
autopurge.purgeInterval=0
maxClientCnxns=60
standaloneEnabled=true
admin.enableServer=true
server.1=0.0.0.0:2888:3888
server.2=192.168.154.33:5889:5890
server.3=192.168.213.91:2888:3888

**Comment by 31z4** [comment]
As per [official documentation](http://zookeeper.apache.org/doc/r3.5.5/zookeeperReconfig.html)

![](https://user-images.githubusercontent.com/3657959/60764194-70d82080-a09e-11e9-9a6b-4578b8b3f0f0.png)

Which means that your `ZOO_SERVERS` is missing the client port part. That's why Zookeeper is not listening it. Runnig as

```
docker run --name my_zookeeper -d -p 2181:2181 -p 2888:2888 -p 3888:3888 --env ZOO_MY_ID=1 --env ZOO_SERVERS="server.1=0.0.0.0:2888:3888;2181 server.2=192.168.154.33:5889:5890 server.3=192.168.213.91:2888:3888" zookeeper:latest
```

should resolve the issue.

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.
