### ISSUE TITLE
Environment variables "reconfigEnabled" no suppoert

### ISSUE THREAD

**Issue by kervin521** [31z4/zookeeper-docker#80]
***Before you file an issue here, please keep in mind that your issue may be not related to the image itself. Please make sure that it is, otherwise report the issue [upstream](https://issues.apache.org/jira/projects/ZOOKEEPER/issues).***

### Expected behavior

Tell us what should happen.

### Actual behavior

Tell us what happens instead.

### Steps to reproduce the behavior

Tell us how to reproduce the issue.

### System configuration

Please include as much relevant information as possible.

**Comment by 31z4** [comment]
Currently I don't have plans to expose `reconfigEnabled` via an environment variable. You can [mount a custom configuration file](https://github.com/31z4/zookeeper-docker#configuration) fo set this option.
