### ISSUE TITLE
zookeeper maxClientCnxns parameter

### ISSUE THREAD

**Issue by engapa** [31z4/zookeeper-docker#9]
We need to update this parameter from docker env variables . I mean , we need to update the zoo.cfg.

In the Dockerfile :

```
ZOO_MAX_CLIENT_CNXNS=60
```

And after the [line](https://github.com/31z4/zookeeper-docker/blob/7e7eac6d6c11428849ec13bb7d240e4cfa21b2e7/3.4.9/docker-entrypoint.sh#L21) we should include:

```
echo "maxClientCnxns=$ZOO_MAX_CLIENT_CNXNS" >> "$CONFIG"
```

**Comment by 31z4** [comment]
Thanks for the report! The idea of having several configuration options as ENV variables is to facilitate tweaking some often changing options and options related to the replicated mode. I'm not going to create an ENV variable for each configuration option. Not a single official image does. Sorry!

**Comment by 31z4** [comment]
Reopening this as there seem to be some demand for this particular parameter.
