### ISSUE TITLE
Are there any instructions to enable SASL authentication with/without SSL in swarm mode?

### ISSUE THREAD

**Issue by xirius** [31z4/zookeeper-docker#93]
Is there any way to enable SASL authentication with/without SSL with the official images in a swarm mode ? Any idea how can it be achieved ? Tutorials ?

**Comment by 31z4** [comment]
No, there is no such instruction. Contributions to https://github.com/docker-library/docs/blob/master/zookeeper/content.md are very welcomed!

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.
